In [1]:
import pandas as pd
import numpy as np

In [2]:
lending_co_data_numeric_NAN2 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_numeric_NAN2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
# 'skip_header=n' will remove the first 2 line of the dataset (becomes convinent when text files include several lines of 
# comments and notes from the authors)
lending_co_data_numeric_NAN2 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',skip_header=2)
lending_co_data_numeric_NAN2

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
# # 'skip_footer=n'
lending_co_data_numeric_NAN2 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',skip_footer=2)
lending_co_data_numeric_NAN2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [7]:
# 'usecols=(0,1,2,...,n)' will tell python we're only interested in the following column
lending_co_data_numeric_NAN2 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                             delimiter=';',
                                             usecols=0)
lending_co_data_numeric_NAN2

array([2000., 2000., 1000., ...,   nan, 1000., 2000.])

In [8]:
lending_co_data_numeric_NAN2 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                             delimiter=';',
                                             usecols=(0,1,5))
lending_co_data_numeric_NAN2

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [9]:
lending_co_data_numeric_NAN2 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                             delimiter=';',
                                             usecols=(0,1,5),
                                            skip_header=2,
                                            skip_footer=2)
lending_co_data_numeric_NAN2

array([[ 1000.,    40., 15340.],
       [ 2000.,    40., 15321.],
       [ 2000.,    50., 13720.],
       ...,
       [ 2000.,    40., 16600.],
       [ 2000.,    40., 16600.],
       [   nan,    40., 16600.]])

In [11]:
lending_co_data_0, lending_co_data_1, lending_co_data_5 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                             delimiter=';',
                                             usecols=(0,1,5),
                                            skip_header=2,
                                            skip_footer=2,
                                            unpack=True)

In [14]:
print(lending_co_data_0)
print(lending_co_data_1)
print(lending_co_data_5)

[1000. 2000. 2000. ... 2000. 2000.   nan]
[40. 40. 50. ... 40. 40. 40.]
[15340. 15321. 13720. ... 16600. 16600. 16600.]
