### Import relevant libraries

In [1]:
import numpy as np

### Scalars

In [2]:
s = 5

In [3]:
s

5

### Vectors

In [6]:
v1 = np.array([5,-2,4]) #row vector

In [14]:
v1

array([ 5, -2,  4])

In [15]:
v2 = np.array([[5],[-2],[4]]) #col vector

In [16]:
v2

array([[ 5],
       [-2],
       [ 4]])

### Matrices

In [12]:
m = np.array([[5,12,6],[-3,0,14]])

In [13]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data Types

In [18]:
type(s)

int

In [19]:
type(v1)

numpy.ndarray

In [20]:
type(m)

numpy.ndarray

In [21]:
s_array = np.array(s)
s_array

array(5)

In [22]:
type(s_array)

numpy.ndarray

### Data Shapes

In [23]:
m.shape

(2, 3)

In [24]:
v1.shape

(3,)

In [25]:
v2.shape

(3, 1)

In [26]:
v1.reshape(1,3)

array([[ 5, -2,  4]])

In [27]:
v1.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [28]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [30]:
s_array.shape

()