### Tensors
* Tensors are multi-dimensional arrays with a uniform type (called a dtype). 
* If you're familiar with NumPy, tensors are (kind of) like np.arrays.
* All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

In [1]:
import numpy as np

In [6]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [7]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [8]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Creating Tensor

In [9]:
t_manual = np.array([
    [[5,12,6],
     [-3,0,14]],
    [[9,8,7],
     [1,3,-5]]
])

In [10]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])