### Addition
* 2 matirces should have same dimensions

In [2]:
import numpy as np

In [3]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [5]:
m3 = m1+m2
m3

array([[14, 20, 13],
       [-2,  3,  9]])

### Subtraction

In [6]:
m4 = m1-m2
m4

array([[-4,  4, -1],
       [-4, -3, 19]])