### Transpose
* To convert row to column or column to row.
* A mxn matrix transposed is a nxm matrix

In [1]:
import numpy as np

In [2]:
a = np.array([[5,12,6],[-3,0,14]])
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
a.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [4]:
c = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
c

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [5]:
c.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

### Transposing Vectors

In [6]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
x.T

array([1, 2, 3])

In [8]:
x.shape

(3,)

In [9]:
x_reshape = x.reshape(1,3)
x_reshape

array([[1, 2, 3]])

In [10]:
x_reshape.T

array([[1],
       [2],
       [3]])