### Dot Product
* The sum of the products of the corresponding elements
* Note: We can only multiply an 'mxn' matrix with an 'nxk' matrix and the output will be 'mxk' matrix

In [1]:
import numpy as np

In [6]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [20]:
x

array([ 2,  8, -4])

In [21]:
y

array([ 1, -7,  3])

In [7]:
np.dot(x,y)

-66

### Scalar.Scalar

In [8]:
np.dot(5,6)

30

In [9]:
np.dot(-10,2)

-20

### Scalar.Vector

In [10]:
x

array([ 2,  8, -4])

In [11]:
5*x

array([ 10,  40, -20])

### Scalar.Matrix

In [12]:
a = np.array([[5,12,6],[-3,0,14]])
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [15]:
np.dot(3,a)

array([[15, 36, 18],
       [-9,  0, 42]])

### Matrix.Matrix

In [16]:
a = np.array([[5,12,6],[-3,0,14]])
b = np.array([[2,-1],[8,0],[3,0]])

In [17]:
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [18]:
b

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [19]:
np.dot(a,b)

array([[124,  -5],
       [ 36,   3]])