In [1]:
import pandas as pd
import numpy as np

In [6]:
price_per_category = pd.Series({'Product A': 22250,'Product B':16600,'Product C':15600})
price_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

### .values

In [7]:
price_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [8]:
type(price_per_category)

pandas.core.series.Series

### .array
* Will convert your Series into a pandas array (an extension array)

In [9]:
price_per_category.array

<PandasArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [10]:
type(price_per_category.array)

pandas.core.arrays.numpy_.PandasArray

### .to_numpy()
* This method has been introduced to satisfy the increased demand for improved transformation of pandas Series into Numpy arrays
* Will organize our information into a pure NumPY array structure

In [12]:
price_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [14]:
type(price_per_category.to_numpy())

numpy.ndarray

In [16]:
# lets suppose you want to change the data type of the data, it won't affect the main Series
test_array = price_per_category[['Product A','Product B']].to_numpy(dtype='float')
test_array

array([22250., 16600.])

In [17]:
type(test_array[0])

numpy.float64

In [20]:
price_per_category.values[0]

22250

In [21]:
type(price_per_category.values[0])

numpy.int64

In [22]:
price_per_category.to_numpy()[0]

22250

In [24]:
type(price_per_category.to_numpy()[0])

numpy.int64